### ISSUE TITLE
build error: invalid conversion

### ISSUE THREAD

**Issue by pitchbent** [alex-konshin/f007th-rpi#14] opened 2022-01-08 17:49 UTC
Hey there,

I am trying to build the project on a raspi 3b+. There seems to be an error with httpd (or maybe I am stupid), but when I run
`/bin/bash f007th-rpi/build.sh` (/bin/sh , as stated in the guide, throws an error concerning popd/pushd)
it won't build. 

This is the output:
```
/bin/bash f007th-rpi/build.sh 
Building on Raspberry Pi 3 Model B Plus Rev 1.3
Build will be done in directory "/home/pi/f007th-rpi/build"

  executable      = f007th-send
  use_gpio_ts     = 1
  include_MQTT    = 0
  include_HTTPD   = 1
  include_DS18B20 = 0

... Procesing file "/home/pi/f007th-rpi/build/common/subdir.mk" ...
... Procesing file "/home/pi/f007th-rpi/build/utils/subdir.mk" ...
... Procesing file "/home/pi/f007th-rpi/build/protocols/subdir.mk" ...
... Procesing file "/home/pi/f007th-rpi/build/subdir.mk" ...
... Procesing file "/home/pi/f007th-rpi/build/objects.mk" ...

... Building ...

Building file: ../utils/HTTPD.cpp
Invoking: Cross G++ Compiler
g++ -std=c++11 -DRPI -DUSE_GPIO_TS -DNDEBUG -DINCLUDE_HTTPD -O2 -Wall -c -fmessage-length=0 -pthread -MMD -MP -MF"utils/HTTPD.d" -MT"utils/HTTPD.o" -o "utils/HTTPD.o" "../utils/HTTPD.cpp"
../utils/HTTPD.cpp: In function ‘int process_params(HTTPD*, MHD_Connection*, const char*, const char**, int, const char**, bool&)’:
../utils/HTTPD.cpp:164:64: error: invalid conversion from ‘int (*)(void*, MHD_ValueKind, const char*, const char*)’ to ‘MHD_KeyValueIterator’ {aka ‘MHD_Result (*)(void*, MHD_ValueKind, const char*, const char*)’} [-fpermissive]
  164 |   MHD_get_connection_values(connection, MHD_GET_ARGUMENT_KIND, &param_iterator, (void*)&req_param_processing_data);
      |                                                                ^~~~~~~~~~~~~~~
      |                                                                |
      |                                                                int (*)(void*, MHD_ValueKind, const char*, const char*)
In file included from ../utils/HTTPD.cpp:12:
/usr/include/microhttpd.h:2714:49: note:   initializing argument 3 of ‘int MHD_get_connection_values(MHD_Connection*, MHD_ValueKind, MHD_KeyValueIterator, void*)’
 2714 |                            MHD_KeyValueIterator iterator,
      |                            ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
../utils/HTTPD.cpp: In static member function ‘static HTTPD* HTTPD::start(SensorsData*, Config*)’:
../utils/HTTPD.cpp:623:9: error: invalid conversion from ‘int (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, size_t*, void**)’ {aka ‘int (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, unsigned int*, void**)’} to ‘MHD_AccessHandlerCallback’ {aka ‘MHD_Result (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, unsigned int*, void**)’} [-fpermissive]
  623 |         &process_request,
      |         ^~~~~~~~~~~~~~~~
      |         |
      |         int (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, size_t*, void**) {aka int (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, unsigned int*, void**)}
In file included from ../utils/HTTPD.cpp:12:
/usr/include/microhttpd.h:2443:45: note:   initializing argument 5 of ‘MHD_Daemon* MHD_start_daemon(unsigned int, uint16_t, MHD_AcceptPolicyCallback, void*, MHD_AccessHandlerCallback, void*, ...)’
 2443 |                   MHD_AccessHandlerCallback dh, void *dh_cls,
      |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
make: *** [utils/subdir.mk:21: utils/HTTPD.o] Error 1
ERROR: Failed to make the executable.
```

Do you have any idea, how to fix it? I googled for a bit, some people seem to have issues with httpd and  the invalid conversion.

Thank you very much for your help.
All the best

**Comment by alex-konshin** [comment] 2022-01-08 21:59
I cannot reproduce the issue on my pi3:

```
pi@rpi3:~ $ cd ~/f007th-rpi/
pi@rpi3:~/f007th-rpi $ /bin/bash ./build.sh
Building on Raspberry Pi 3 Model B Rev 1.2
Build will be done in directory "/home/pi/f007th-rpi/build"

  executable      = f007th-send
  use_gpio_ts     = 1
  include_MQTT    = 0
  include_HTTPD   = 1
  include_DS18B20 = 0

... Procesing file "/home/pi/f007th-rpi/build/common/subdir.mk" ...
... Procesing file "/home/pi/f007th-rpi/build/utils/subdir.mk" ...
... Procesing file "/home/pi/f007th-rpi/build/protocols/subdir.mk" ...
... Procesing file "/home/pi/f007th-rpi/build/subdir.mk" ...
... Procesing file "/home/pi/f007th-rpi/build/objects.mk" ...

... Building ...

Building file: ../utils/HTTPD.cpp
Invoking: Cross G++ Compiler
g++ -std=c++11 -DRPI -DUSE_GPIO_TS -DNDEBUG -DINCLUDE_HTTPD -O2 -Wall -c -fmessage-length=0 -pthread -MMD -MP -MF"utils/HTTPD.d" -MT"utils/HTTPD.o" -o "utils/HTTPD.o" "../utils/HTTPD.cpp"
Finished building: ../utils/HTTPD.cpp

Building file: ../utils/Logger.cpp
Invoking: Cross G++ Compiler
g++ -std=c++11 -DRPI -DUSE_GPIO_TS -DNDEBUG -DINCLUDE_HTTPD -O2 -Wall -c -fmessage-length=0 -pthread -MMD -MP -MF"utils/Logger.d" -MT"utils/Logger.o" -o "utils/Logger.o" "../utils/Logger.cpp"
Finished building: ../utils/Logger.cpp

....
```

**Comment by pitchbent** [comment] 2022-01-10 09:18
That's weird.
I reflashed the sd card and tried again, with a full apt update/upgrade and the error persists.

**Comment by grutzifix** [comment] 2022-01-12 18:24
> That's weird. I reflashed the sd card and tried again, with a full apt update/upgrade and the error persists.

Same here with fresh r-pi 3b+

**Comment by grutzifix** [comment] 2022-01-12 18:27
```
pi@raspberrypi:~ $ /bin/bash f007th-rpi/build.sh
Building on Raspberry Pi 3 Model B Plus Rev 1.3
Build will be done in directory "/home/pi/f007th-rpi/build"

  executable      = f007th-send
  use_gpio_ts     = 1
  include_MQTT    = 0
  include_HTTPD   = 1
  include_DS18B20 = 0

... Procesing file "/home/pi/f007th-rpi/build/common/subdir.mk" ...
... Procesing file "/home/pi/f007th-rpi/build/utils/subdir.mk" ...
... Procesing file "/home/pi/f007th-rpi/build/protocols/subdir.mk" ...
... Procesing file "/home/pi/f007th-rpi/build/subdir.mk" ...
... Procesing file "/home/pi/f007th-rpi/build/objects.mk" ...

... Building ...

Building file: ../utils/HTTPD.cpp
Invoking: Cross G++ Compiler
g++ -std=c++11 -DRPI -DUSE_GPIO_TS -DNDEBUG -DINCLUDE_HTTPD -O2 -Wall -c -fmessage-length=0 -pthread -MMD -MP -MF"utils/HTTPD.d" -MT"utils/HTTPD.o" -o "utils/HTTPD.o" "../utils/HTTPD.cpp"
../utils/HTTPD.cpp: In function ‘int process_params(HTTPD*, MHD_Connection*, const char*, const char**, int, const char**, bool&)’:
../utils/HTTPD.cpp:164:64: error: invalid conversion from ‘int (*)(void*, MHD_ValueKind, const char*, const char*)’ to ‘MHD_KeyValueIterator’ {aka ‘MHD_Result (*)(void*, MHD_ValueKind, const char*, const char*)’} [-fpermissive]
  164 |   MHD_get_connection_values(connection, MHD_GET_ARGUMENT_KIND, &param_iterator, (void*)&req_param_processing_data);
      |                                                                ^~~~~~~~~~~~~~~
      |                                                                |
      |                                                                int (*)(void*, MHD_ValueKind, const char*, const char*)
In file included from ../utils/HTTPD.cpp:12:
/usr/include/microhttpd.h:2714:49: note:   initializing argument 3 of ‘int MHD_get_connection_values(MHD_Connection*, MHD_ValueKind, MHD_KeyValueIterator, void*)’
 2714 |                            MHD_KeyValueIterator iterator,
      |                            ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
../utils/HTTPD.cpp: In static member function ‘static HTTPD* HTTPD::start(SensorsData*, Config*)’:
../utils/HTTPD.cpp:623:9: error: invalid conversion from ‘int (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, size_t*, void**)’ {aka ‘int (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, unsigned int*, void**)’} to ‘MHD_AccessHandlerCallback’ {aka ‘MHD_Result (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, unsigned int*, void**)’} [-fpermissive]
  623 |         &process_request,
      |         ^~~~~~~~~~~~~~~~
      |         |
      |         int (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, size_t*, void**) {aka int (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, unsigned int*, void**)}
In file included from ../utils/HTTPD.cpp:12:
/usr/include/microhttpd.h:2443:45: note:   initializing argument 5 of ‘MHD_Daemon* MHD_start_daemon(unsigned int, uint16_t, MHD_AcceptPolicyCallback, void*, MHD_AccessHandlerCallback, void*, ...)’
 2443 |                   MHD_AccessHandlerCallback dh, void *dh_cls,
      |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
make: *** [utils/subdir.mk:21: utils/HTTPD.o] Error 1
ERROR: Failed to make the executable.
```

**Comment by pitchbent** [comment] 2022-01-12 21:12
Adding -fpermissive to build.sh in line 124 seems to solve it. Can anyone verifiy it?

**Comment by grutzifix** [comment] 2022-01-12 21:42
sry Im such a noob 

thats line 124:
```
  compile='\tg++ -std=c++11 '${options}' -O2 -Wall -c -fmessage-length=0 -pthread'${platform_options}' -MMD -MP -MF\"$(@:%.o=%.d)\" -MT\"$(@)\" -o \"$@\" \"$<\"'
  ```
  where do I put it in?

**Comment by pitchbent** [comment] 2022-01-12 21:50
I put it before `-MMD`, but you can probably put it wherever you want as long it is on the right hand side of the first equal sign. Kruzifix! :,D

**Comment by grutzifix** [comment] 2022-01-12 22:07
I think I did it correct, but its the same error as before

**Comment by grutzifix** [comment] 2022-01-12 22:12
whats the best way to make a change in build.sh?
I made a new build.sh with nano in the same folder, copied the origial build.sh in it and changed line 124

**Comment by grutzifix** [comment] 2022-01-12 23:17
i think it works

**Comment by grutzifix** [comment] 2022-01-12 23:19
or not
```
pi@raspberrypi:~ $ /bin/bash f007th-rpi/build.sh
Building on Raspberry Pi 3 Model B Plus Rev 1.3
Build will be done in directory "/home/pi/f007th-rpi/build"

  executable      = f007th-send
  use_gpio_ts     = 1
  include_MQTT    = 0
  include_HTTPD   = 1
  include_DS18B20 = 0

... Procesing file "/home/pi/f007th-rpi/build/common/subdir.mk" ...
... Procesing file "/home/pi/f007th-rpi/build/utils/subdir.mk" ...
... Procesing file "/home/pi/f007th-rpi/build/protocols/subdir.mk" ...
... Procesing file "/home/pi/f007th-rpi/build/subdir.mk" ...
... Procesing file "/home/pi/f007th-rpi/build/objects.mk" ...

... Building ...

Building file: ../utils/HTTPD.cpp
Invoking: Cross G++ Compiler
g++ -std=c++11 -DRPI -DUSE_GPIO_TS -DNDEBUG -DINCLUDE_HTTPD -O2 -Wall -c -fmessage-length=0 -pthread -fpermissive -MMD -MP -MF"utils/HTTPD.d" -MT"utils/HTTPD.o" -o "utils/HTTPD.o" "../utils/HTTPD.cpp"
../utils/HTTPD.cpp: In function ‘int process_params(HTTPD*, MHD_Connection*, const char*, const char**, int, const char**, bool&)’:
../utils/HTTPD.cpp:164:64: warning: invalid conversion from ‘int (*)(void*, MHD_ValueKind, const char*, const char*)’ to ‘MHD_KeyValueIterator’ {aka ‘MHD_Result (*)(void*, MHD_ValueKind, const char*, const char*)’} [-fpermissive]
  164 |   MHD_get_connection_values(connection, MHD_GET_ARGUMENT_KIND, &param_iterator, (void*)&req_param_processing_data);
      |                                                                ^~~~~~~~~~~~~~~
      |                                                                |
      |                                                                int (*)(void*, MHD_ValueKind, const char*, const char*)
In file included from ../utils/HTTPD.cpp:12:
/usr/include/microhttpd.h:2714:49: note:   initializing argument 3 of ‘int MHD_get_connection_values(MHD_Connection*, MHD_ValueKind, MHD_KeyValueIterator, void*)’
 2714 |                            MHD_KeyValueIterator iterator,
      |                            ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
../utils/HTTPD.cpp: In static member function ‘static HTTPD* HTTPD::start(SensorsData*, Config*)’:
../utils/HTTPD.cpp:623:9: warning: invalid conversion from ‘int (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, size_t*, void**)’ {aka ‘int (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, unsigned int*, void**)’} to ‘MHD_AccessHandlerCallback’ {aka ‘MHD_Result (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, unsigned int*, void**)’} [-fpermissive]
  623 |         &process_request,
      |         ^~~~~~~~~~~~~~~~
      |         |
      |         int (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, size_t*, void**) {aka int (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, unsigned int*, void**)}
In file included from ../utils/HTTPD.cpp:12:
/usr/include/microhttpd.h:2443:45: note:   initializing argument 5 of ‘MHD_Daemon* MHD_start_daemon(unsigned int, uint16_t, MHD_AcceptPolicyCallback, void*, MHD_AccessHandlerCallback, void*, ...)’
 2443 |                   MHD_AccessHandlerCallback dh, void *dh_cls,
      |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
Finished building: ../utils/HTTPD.cpp

Building file: ../utils/Logger.cpp
Invoking: Cross G++ Compiler
g++ -std=c++11 -DRPI -DUSE_GPIO_TS -DNDEBUG -DINCLUDE_HTTPD -O2 -Wall -c -fmessage-length=0 -pthread -fpermissive -MMD -MP -MF"utils/Logger.d" -MT"utils/Logger.o" -o "utils/Logger.o" "../utils/Logger.cpp"
Finished building: ../utils/Logger.cpp

Building file: ../utils/Utils.cpp
Invoking: Cross G++ Compiler
g++ -std=c++11 -DRPI -DUSE_GPIO_TS -DNDEBUG -DINCLUDE_HTTPD -O2 -Wall -c -fmessage-length=0 -pthread -fpermissive -MMD -MP -MF"utils/Utils.d" -MT"utils/Utils.o" -o "utils/Utils.o" "../utils/Utils.cpp"
Finished building: ../utils/Utils.cpp

Building file: ../protocols/AcuRite00592TXR.cpp
Invoking: Cross G++ Compiler
g++ -std=c++11 -DRPI -DUSE_GPIO_TS -DNDEBUG -DINCLUDE_HTTPD -O2 -Wall -c -fmessage-length=0 -pthread -fpermissive -MMD -MP -MF"protocols/AcuRite00592TXR.d" -MT"protocols/AcuRite00592TXR.o" -o "protocols/AcuRite00592TXR.o" "../protocols/AcuRite00592TXR.cpp"
Finished building: ../protocols/AcuRite00592TXR.cpp

Building file: ../protocols/AmbientWeatherF007TH.cpp
Invoking: Cross G++ Compiler
g++ -std=c++11 -DRPI -DUSE_GPIO_TS -DNDEBUG -DINCLUDE_HTTPD -O2 -Wall -c -fmessage-length=0 -pthread -fpermissive -MMD -MP -MF"protocols/AmbientWeatherF007TH.d" -MT"protocols/AmbientWeatherF007TH.o" -o "protocols/AmbientWeatherF007TH.o" "../protocols/AmbientWeatherF007TH.cpp"
Finished building: ../protocols/AmbientWeatherF007TH.cpp

Building file: ../protocols/AuriolHG02832.cpp
Invoking: Cross G++ Compiler
g++ -std=c++11 -DRPI -DUSE_GPIO_TS -DNDEBUG -DINCLUDE_HTTPD -O2 -Wall -c -fmessage-length=0 -pthread -fpermissive -MMD -MP -MF"protocols/AuriolHG02832.d" -MT"protocols/AuriolHG02832.o" -o "protocols/AuriolHG02832.o" "../protocols/AuriolHG02832.cpp"
Finished building: ../protocols/AuriolHG02832.cpp

Building file: ../protocols/LaCrosseTX7.cpp
Invoking: Cross G++ Compiler
g++ -std=c++11 -DRPI -DUSE_GPIO_TS -DNDEBUG -DINCLUDE_HTTPD -O2 -Wall -c -fmessage-length=0 -pthread -fpermissive -MMD -MP -MF"protocols/LaCrosseTX7.d" -MT"protocols/LaCrosseTX7.o" -o "protocols/LaCrosseTX7.o" "../protocols/LaCrosseTX7.cpp"
Finished building: ../protocols/LaCrosseTX7.cpp

Building file: ../protocols/Protocol.cpp
Invoking: Cross G++ Compiler
g++ -std=c++11 -DRPI -DUSE_GPIO_TS -DNDEBUG -DINCLUDE_HTTPD -O2 -Wall -c -fmessage-length=0 -pthread -fpermissive -MMD -MP -MF"protocols/Protocol.d" -MT"protocols/Protocol.o" -o "protocols/Protocol.o" "../protocols/Protocol.cpp"
Finished building: ../protocols/Protocol.cpp

Building file: ../protocols/TFATwinPlus.cpp
Invoking: Cross G++ Compiler
g++ -std=c++11 -DRPI -DUSE_GPIO_TS -DNDEBUG -DINCLUDE_HTTPD -O2 -Wall -c -fmessage-length=0 -pthread -fpermissive -MMD -MP -MF"protocols/TFATwinPlus.d" -MT"protocols/TFATwinPlus.o" -o "protocols/TFATwinPlus.o" "../protocols/TFATwinPlus.cpp"
Finished building: ../protocols/TFATwinPlus.cpp

Building file: ../protocols/WH2.cpp
Invoking: Cross G++ Compiler
g++ -std=c++11 -DRPI -DUSE_GPIO_TS -DNDEBUG -DINCLUDE_HTTPD -O2 -Wall -c -fmessage-length=0 -pthread -fpermissive -MMD -MP -MF"protocols/WH2.d" -MT"protocols/WH2.o" -o "protocols/WH2.o" "../protocols/WH2.cpp"
Finished building: ../protocols/WH2.cpp

Building file: ../common/Config.cpp
Invoking: Cross G++ Compiler
g++ -std=c++11 -DRPI -DUSE_GPIO_TS -DNDEBUG -DINCLUDE_HTTPD -O2 -Wall -c -fmessage-length=0 -pthread -fpermissive -MMD -MP -MF"common/Config.d" -MT"common/Config.o" -o "common/Config.o" "../common/Config.cpp"
Finished building: ../common/Config.cpp

Building file: ../common/ConfigParser.cpp
Invoking: Cross G++ Compiler
g++ -std=c++11 -DRPI -DUSE_GPIO_TS -DNDEBUG -DINCLUDE_HTTPD -O2 -Wall -c -fmessage-length=0 -pthread -fpermissive -MMD -MP -MF"common/ConfigParser.d" -MT"common/ConfigParser.o" -o "common/ConfigParser.o" "../common/ConfigParser.cpp"
Finished building: ../common/ConfigParser.cpp

Building file: ../common/Receiver.cpp
Invoking: Cross G++ Compiler
g++ -std=c++11 -DRPI -DUSE_GPIO_TS -DNDEBUG -DINCLUDE_HTTPD -O2 -Wall -c -fmessage-length=0 -pthread -fpermissive -MMD -MP -MF"common/Receiver.d" -MT"common/Receiver.o" -o "common/Receiver.o" "../common/Receiver.cpp"
Finished building: ../common/Receiver.cpp

Building file: ../common/SensorsData.cpp
Invoking: Cross G++ Compiler
g++ -std=c++11 -DRPI -DUSE_GPIO_TS -DNDEBUG -DINCLUDE_HTTPD -O2 -Wall -c -fmessage-length=0 -pthread -fpermissive -MMD -MP -MF"common/SensorsData.d" -MT"common/SensorsData.o" -o "common/SensorsData.o" "../common/SensorsData.cpp"
Finished building: ../common/SensorsData.cpp

Building file: ../f007th_send.cpp
Invoking: Cross G++ Compiler
g++ -std=c++11 -DRPI -DUSE_GPIO_TS -DNDEBUG -DINCLUDE_HTTPD -O2 -Wall -c -fmessage-length=0 -pthread -fpermissive -MMD -MP -MF"f007th_send.d" -MT"f007th_send.o" -o "f007th_send.o" "../f007th_send.cpp"
Finished building: ../f007th_send.cpp

Building target: f007th-send
Invoking: Cross G++ Linker
g++ -pthread -o "f007th-send" ./utils/HTTPD.o ./utils/Logger.o ./utils/Utils.o  ./protocols/AcuRite00592TXR.o ./protocols/AmbientWeatherF007TH.o ./protocols/AuriolHG02832.o ./protocols/LaCrosseTX7.o ./protocols/Protocol.o ./protocols/TFATwinPlus.o ./protocols/WH2.o  ./common/Config.o ./common/ConfigParser.o ./common/Receiver.o ./common/SensorsData.o  ./f007th_send.o   -lrt -lcurl -lmicrohttpd
Finished building target: f007th-send

Executale "/home/pi/f007th-rpi/build/f007th-send" has been built successfully.

cp: cannot create regular file '/home/pi/f007th-rpi/bin/': Not a directory
ERROR: Failed to copy file "/home/pi/f007th-rpi/build/f007th-send" to directory "/home/pi/f007th-rpi/bin/".
``

**Comment by grutzifix** [comment] 2022-01-12 23:32
i make the directory manually f007th-rpi/bin/

so:
Finished building target: f007th-send

Executale "/home/pi/f007th-rpi/build/f007th-send" has been built successfully.

File "/home/pi/f007th-rpi/build/f007th-send" has been copied to directory "/home/pi/f007th-rpi/bin/".

Done.

**Comment by alex-konshin** [comment] 2022-04-10 02:42
The issue happens on 64-bit OS only.
It is fixed now.

**Closed** 2022-06-19 02:49 UTC
